apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
  namespace: openshift-operators

data:
  application.yml: |
    akhq:
      connections:
        kafka-cluster:
          properties:
            bootstrap.servers: "kafka-cluster-kafka-bootstrap.openshift-operators.svc:9092"

    micronaut:
      security:
        enabled: false